### ISSUE TITLE
Is there a way to execute a stand-alone expression?

### ISSUE THREAD

**Issue by Arshia001** [sebastienros/jint#1187]
The engine only accepts complete scripts. Also, the constructor for NodeList is internal, meaning you can't create new scripts in user code. Is there a way to evaluate expression nodes directly? This is useful for implementing e.g. simple one-line calculations in a system's configuration, while disallowing complex scripts, like so:

```yaml
some-config:
  some-item:
    preprocess: x + 12 * 8 - 1
```
